Merge pull request #27 from emerson-eps/dependabot/npm_and_yarn/browserify-sign-4.2.2
syss69/elephantgame pull request #1
Opened 2024-01-12 12:35 UTC by syss69

Images added

2024-01-14 08:57 UTC, clairecassan requested changes

2024-01-14 08:57 UTC, clairecassan commented on src/App.tsx
> +        <img src="https://api.dicebear.com/7.x/fun-emoji/svg?seed=Ginger" height="auto" width={150} alt="Smile" id='smile' />
Next task can be to randomize the placement. We will add it to the sprint tomorrow

2024-01-14 08:57 UTC, clairecassan commented on src/App.test.tsx
>  });
You are missing a test for the "image" feature that you implemented

2024-01-15 14:12 UTC, clairecassan approved these changes

2024-01-15 14:12 UTC, clairecassan commented on src/App.css
> +    backface-visibility: visible;
unused: please remove

2024-01-15 14:13 UTC, clairecassan approved these changes

2024-01-15 14:23 UTC, merged

2024-01-15 15:08 UTC, syss69 commented
Why do I need to remove it?

пн, 15 янв. 2024 г. в 15:12, clairecassan ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/App.css
> <https://github.com/syss69/elephantgame/pull/1#discussion_r1452426044>:
>
> > \ No newline at end of file
> +  img {
> +    border:5px solid black;
> +    margin: 1rem;
> +    backface-visibility: visible;
>
> unused: please remove
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/syss69/elephantgame/pull/1#pullrequestreview-1821766134>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATL57F3WERK4MXEGULFKN2DYOU2OFAVCNFSM6AAAAABBYCCSBKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMRRG43DMMJTGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>